resource_types:
  - name: binary
    type: docker-image
    source:
      repository: medoror/binary-resource
      tag: 0.0.1
resources:
  - name: om
    type: binary
    source:
      repo: pivotal-cf/om
      tag: 4.6.0

jobs:
  - name: hello-world
    plan:
      - get: om
        trigger: true
      - task: hello-world
        config:
          inputs:
            - name: om
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          run:
            path: cat
            args: ["yo"]