image-config: &image-config
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: alpine
      tag: "latest"

resource_types:
  - name: binary
    type: docker-image
    source:
      repository: medoror/github-binary-resource
resources:
  - name: om
    type: binary
    source:
      repo: pivotal-cf/om
      tag: 4.6.0

jobs:
  - name: om-binary-test
    plan:
      - get: om
        trigger: true
      - task: print-om-version
        config:
          <<: *image-config
          inputs:
            - name: om
          run:
            path: om
            args: ["version"]